[build]
  command = "pnpm build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/8"
  to = "/8/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/8/"
  to = "/8/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/7"
  to = "/7/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/7/"
  to = "/7/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/6"
  to = "/6/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/6/"
  to = "/6/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/5"
  to = "/5/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/5/"
  to = "/5/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/4"
  to = "/4/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/4/"
  to = "/4/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/3/1"
  to = "/3/1/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/3/1/"
  to = "/3/1/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/3/2"
  to = "/3/2/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/3/2/"
  to = "/3/2/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/3"
  to = "/3/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/3/"
  to = "/3/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/1"
  to = "/1/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/2"
  to = "/2/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/2/"
  to = "/2/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/1/"
  to = "/1/index.html"
  status = 200
  force = true
