import '../../shared/navigation.css';
import './style.css';
import {navigation,bindNavigation} from '../../shared/navigation.js';
import {createGame,createPuzzle,stages,tuning,switchPosition,pressureValue,pressureAccepted,syncAccepted} from './game.js';
import {sealSvg,sealDescription} from './symbols.js';
import {bindScratch} from './scratch.js';
import {createAmbience} from './audio.js';

if(location.pathname==='/7/')history.replaceState(null,'',`/7${location.search}`);
const preview=new URLSearchParams(location.search).has('apercu');
if(preview)document.documentElement.classList.add('is-apercu');
const bomb='<svg viewBox="0 0 32 32" fill="none" aria-hidden="true"><circle cx="14" cy="20" r="10" fill="currentColor"/><path d="m19 11 3-4 4 2m-2-3 2-4M27 6h4M22 2l-1-2" stroke="currentColor" stroke-width="2"/><path d="M8 18q0-4 4-5" stroke="#150e10" stroke-width="2" stroke-linecap="round"/></svg>';
document.querySelector('#app').innerHTML=`<div class="panic-shell">
 <header class="site-header"><a class="brand" href="/" aria-label="Panique, retour au calendrier">${bomb}<span>panique<span class="brand-dot">.</span></span></a>${navigation(7)}</header>
 <main><div class="mission-title"><div><span class="eyebrow">PROTOCOLE 07 / DÉSAMORÇAGE</span><h1>LE CALME <span>AVANT LA FIN.</span></h1></div><button id="sound" aria-pressed="false" aria-label="Couper le son">♫ <span>SON ACTIVÉ</span></button></div>
 <div class="game-layout"><section class="device" aria-label="Pupitre de désamorçage">
  <i class="screw tl"></i><i class="screw tr"></i><i class="screw bl"></i><i class="screw br"></i>
  <div class="device-top"><span class="device-model">PNQ—07 <small>SYSTÈME AUTONOME</small></span><span class="armed"><i></i><span id="armed-text">EN ATTENTE</span></span></div>
  <div class="timer-housing"><span class="timer-caption">TEMPS AVANT EXTINCTION</span><div id="countdown" role="timer" aria-label="Temps restant" aria-live="off">01:00<span>.00</span></div><div class="timer-bottom"><span id="penalty">60 SECONDES. PAS UNE DE PLUS.</span><span class="signal">▂ ▃ ▅ ▆ ▇</span></div></div>
  <div class="lock-leds" aria-label="Progression">${stages.map((s,i)=>`<span class="lock-led" id="led-${i}" title="${s[0]}"><i></i><small>${String(i+1).padStart(2,'0')}</small></span>`).join('')}</div>
  <div class="module" id="module"></div>
  <div class="device-bottom"><span>NE PAS SE LAISSER DISTRAIRE.</span><div class="barcode" aria-hidden="true"></div><span>№ 2026—007</span></div>
 </section>
 </div>
 </main><footer><span>WEBTOBER / 07 OCTOBRE 2026</span><button id="restart">↻ Recommencer</button></footer>
 <p class="sr-only" id="announcement" role="status" aria-live="polite"></p>
</div><dialog id="concept"><button id="close-concept" aria-label="Fermer">×</button><span class="eyebrow">UN THÈME, UNE HERO SECTION</span><h2>Panique.</h2><p>Dix petits défis à résoudre en une minute. Chaque erreur retire trois secondes. Les verrous changent à chaque partie.</p><p>Le son peut être coupé à tout moment. La minuterie continue si vous quittez l’onglet ou ouvrez ce panneau.</p><button class="small-button" id="back-game">Compris</button></dialog>`;
bindNavigation();
const $=s=>document.querySelector(s),game=createGame(),audio=createAmbience();
let puzzle,frame,stepStarted=0,progress=0,selected=null,matched=new Set(),holding=null,holdFrame,capOpen=false,finished=false,memoryReady=false,memoryTimers=[];
const announce=text=>{$('#announcement').textContent=text;};
function clearModule(){memoryTimers.forEach(clearTimeout);memoryTimers=[];cancelAnimationFrame(holdFrame);holding=null;}
function header(){return `<div class="module-heading"><span>VERROU ${String(game.state.step+1).padStart(2,'0')} / 10</span><h3>${stages[game.state.step][0]}</h3><p>${stages[game.state.step][1]}</p></div>`;}
function ready(){cancelAnimationFrame(frame);clearModule();audio.stop(true);game.state.phase='ready';finished=false;document.body.dataset.phase='ready';delete document.body.dataset.step;document.body.classList.remove('critical');$('#armed-text').textContent='EN ATTENTE';$('#countdown').innerHTML='01:00<span>.00</span>';$('#penalty').textContent='60 SECONDES. PAS UNE DE PLUS.';for(let i=0;i<10;i++)$(`#led-${i}`).className='lock-led';$('#module').innerHTML=`<div class="intro"><span class="intro-warning">⚠ COMPTE À REBOURS IMMINENT</span><h3>Vous avez<br/><em>une minute.</em></h3><p>Dix verrous à ouvrir.<br/>Chaque erreur coûte trois secondes.</p><button class="play" id="play" ${preview?'disabled':''}>PLAY <span>↗</span></button></div>`;if(!preview)$('#play').addEventListener('click',start);}
function start(){clearModule();puzzle=createPuzzle();game.start();finished=false;document.body.dataset.phase='playing';$('#armed-text').textContent='ARMÉ';$('#penalty').textContent='60 SECONDES. PAS UNE DE PLUS.';audio.start().catch(()=>{announce('Son indisponible. Le jeu reste jouable sans son.');});showStep();loop();}
function updateProgress(){for(let i=0;i<10;i++)$(`#led-${i}`).className=`lock-led ${i<game.state.step?'done':i===game.state.step?'active':''}`;}
function done(){const step=game.state.step;if(!game.complete(step)){if(game.state.phase==='lost')end();return;}audio.success();updateProgress();if(game.state.phase==='won')end();else showStep();}
function error(){if(!game.mistake())return;audio.error();$('#penalty').textContent=`ERREUR ${String(game.state.errors).padStart(2,'0')} · −03 SECONDES`;$('#module').classList.remove('mistake');void $('#module').offsetWidth;$('#module').classList.add('mistake');announce('Erreur. Trois secondes perdues.');if(game.state.phase==='lost')end();}
function showStep(){clearModule();progress=0;selected=null;matched=new Set();capOpen=false;memoryReady=false;stepStarted=performance.now();updateProgress();const step=game.state.step;document.body.dataset.step=String(step);let content='';
 if(step===0)content=`<div class="switches">${Array.from({length:4},(_,i)=>`<button class="toggle moving" data-switch="${i}" aria-label="Arrêter l’interrupteur ${i+1} en bas"><i><b></b><em></em></i><span>${String(i+1).padStart(2,'0')}</span></button>`).join('')}</div><span class="module-hint" id="switch-progress">0 / 4 ARRÊTÉS</span>`;
 if(step===1)content=`<div class="code-label">CODE D’ACCÈS<div class="scratch-ticket"><strong id="true-code" aria-hidden="true">${puzzle.code}</strong><canvas id="code-scratch" width="240" height="96" tabindex="0" role="button" aria-label="Code affiché ${puzzle.fakeCode}. Gratter pour révéler le vrai code" aria-description="Glissez sur l’étiquette. Au clavier, appuyez plusieurs fois sur Espace ou Entrée."></canvas></div><span id="scratch-hint">GRATTEZ L’ÉTIQUETTE</span></div><div class="code-entry" aria-label="Code saisi">_ _ _</div><div class="keypad">${['1','2','3','4','5','6','7','8','9','⌫','0','↵'].map(n=>`<button data-key="${n}" aria-label="${n==='⌫'?'Effacer':n==='↵'?'Valider':n}">${n}</button>`).join('')}</div>`;
 if(step===2)content=`<div class="symbol-target" aria-label="Ordre à reproduire">${puzzle.symbols.map(s=>`<span data-target-symbol="${s}" aria-label="${sealDescription(s)}">${sealSvg(s)}</span>`).join('')}</div><div class="seal-grid">${puzzle.buttons.map(s=>`<button data-symbol="${s}" aria-label="${sealDescription(s)}">${sealSvg(s)}</button>`).join('')}</div><span class="module-hint" id="sequence-progress">0 / 3</span>`;
 if(step===3)content=`<div class="dial" aria-hidden="true"><div class="dial-ticks"></div><i id="needle"></i><strong id="dial-value">50</strong></div><label class="frequency" for="frequency">FRÉQUENCE CIBLE <strong>${puzzle.dial}</strong></label><input type="range" id="frequency" min="0" max="100" value="50"/><button class="small-button" id="check-dial">VERROUILLER</button>`;
 if(step===4)content=`<div class="connection-board"><div>${['◆','●','▲'].map(s=>`<button data-left="${s}" aria-label="Prise ${s}">${s}<i></i></button>`).join('')}</div><svg aria-hidden="true" viewBox="0 0 100 160" preserveAspectRatio="none" id="cables"></svg><div>${puzzle.connections.map(s=>`<button data-right="${s}" aria-label="Connecteur ${s}"><i></i>${s}</button>`).join('')}</div></div><span class="module-hint">CHOISISSEZ UNE PRISE, PUIS SON CONNECTEUR.</span>`;
 if(step===5)content=`<div class="memory-status" id="memory-status">REGARDEZ LA SÉQUENCE…</div><div class="memory-buttons">${['A','B','C','D'].map((s,i)=>`<button data-memory="${i}" disabled aria-label="Lumière ${s}"><i></i><span>${s}</span></button>`).join('')}</div><span class="module-hint" id="memory-progress">${puzzle.memory.length} LUMIÈRES À MÉMORISER</span>`;
 if(step===6)content=`<div class="pressure-track"><span class="safe-zone"></span><i id="pressure-fill"></i></div><div class="pressure-legend"><span>0</span><span>ZONE VERTE</span><span>100</span></div><button class="hold-button" id="pressure">MAINTENIR <span>PUIS RELÂCHER</span></button>`;
 if(step===7)content=`<div class="odd-grid">${Array.from({length:9},(_,i)=>`<button data-odd="${i}" aria-label="Symbole ${i+1} : ${i===puzzle.odd?puzzle.oddShape:puzzle.shape}">${i===puzzle.odd?puzzle.oddShape:puzzle.shape}</button>`).join('')}</div>`;
 if(step===8)content=`<div class="sync-track"><i id="sync-a"></i><i id="sync-b"></i></div><button class="hold-button" id="sync">SYNCHRONISER <span>AU CROISEMENT DES REPÈRES</span></button>`;
 if(step===9)content=`<div class="final-lock"><button id="cap" aria-expanded="false">SOULEVER LE CAPOT <span>↗</span></button><button id="disarm" class="hold-button" disabled>DÉSAMORCER <span>MAINTENEZ 2 SECONDES</span></button><div class="final-progress"><i id="final-fill"></i></div></div>`;
 $('#module').innerHTML=header()+`<div class="module-content stage-${step}">${content}</div>`;announce(`Verrou ${step+1}. ${stages[step][0]}. ${stages[step][1]}`);bindStep(step);
}
function bindStep(step){
 if(step===0)document.querySelectorAll('[data-switch]').forEach(b=>{
  const stop=()=>{const index=Number(b.dataset.switch);if(matched.has(index)||game.state.phase!=='playing')return;const position=Number(b.style.getPropertyValue('--switch-position').replace('%',''));if(position<tuning.switchThreshold){error();return;}matched.add(index);b.disabled=true;b.classList.replace('moving','stopped');b.style.setProperty('--switch-position','100%');b.setAttribute('aria-label',`Interrupteur ${index+1} arrêté en bas`);$('#switch-progress').textContent=`${matched.size} / 4 ARRÊTÉS`;if(matched.size===4)done();};
  b.onpointerdown=e=>{if(e.button===0)stop();};
  b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();if(!e.repeat)stop();}};
  b.onclick=e=>{if(e.detail===0)stop();};
 });
 if(step===1){bindScratch($('#code-scratch'),puzzle.fakeCode,()=>{$('#true-code').removeAttribute('aria-hidden');$('#scratch-hint').textContent='CODE RÉVÉLÉ';announce(`Code révélé : ${puzzle.code.split('').join(' ')}.`);});let code='';function key(k){if(k==='⌫')code=code.slice(0,-1);else if(k==='↵'){if(code===puzzle.code){done();return;}error();code='';}else if(code.length<3)code+=k;if(game.state.phase==='playing')$('.code-entry').textContent=(code+'___').split('').join(' ').slice(0,5);}document.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>key(b.dataset.key));}
 if(step===2)document.querySelectorAll('[data-symbol]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.symbol)!==puzzle.symbols[progress]){error();progress=0;}else progress++;if(game.state.phase!=='playing')return;document.querySelectorAll('[data-target-symbol]').forEach((target,i)=>target.classList.toggle('matched',i<progress));if(progress===3)done();else $('#sequence-progress').textContent=`${progress} / 3`;});
 if(step===3){const range=$('#frequency');const draw=()=>{$('#needle').style.rotate=`${-120+Number(range.value)*2.4}deg`;$('#dial-value').textContent=range.value;};range.oninput=draw;draw();$('#check-dial').onclick=()=>Math.abs(Number(range.value)-puzzle.dial)<=3?done():error();}
 if(step===4){document.querySelectorAll('[data-left]').forEach(b=>b.onclick=()=>{if(matched.has(b.dataset.left))return;selected=b.dataset.left;document.querySelectorAll('[data-left]').forEach(x=>x.classList.toggle('selected',x===b));});document.querySelectorAll('[data-right]').forEach(b=>b.onclick=()=>{if(!selected||matched.has(b.dataset.right))return;if(selected!==b.dataset.right){error();return;}matched.add(selected);const left=document.querySelector(`[data-left="${selected}"]`);left.disabled=true;b.disabled=true;left.classList.add('connected');b.classList.add('connected');const y1=['◆','●','▲'].indexOf(selected)*53+27,y2=puzzle.connections.indexOf(selected)*53+27;$('#cables').insertAdjacentHTML('beforeend',`<path d="M0 ${y1} C40 ${y1} 60 ${y2} 100 ${y2}"/>`);selected=null;if(matched.size===3)done();});}
 if(step===5){puzzle.memory.forEach((n,i)=>{memoryTimers.push(setTimeout(()=>{const b=document.querySelector(`[data-memory="${n}"]`);b?.classList.add('lit');},300+i*650),setTimeout(()=>document.querySelector(`[data-memory="${n}"]`)?.classList.remove('lit'),750+i*650));});memoryTimers.push(setTimeout(()=>{memoryReady=true;$('#memory-status').textContent='À VOUS DE JOUER';document.querySelectorAll('[data-memory]').forEach(b=>b.disabled=false);},300+puzzle.memory.length*650));document.querySelectorAll('[data-memory]').forEach(b=>b.onclick=()=>{if(!memoryReady)return;if(Number(b.dataset.memory)!==puzzle.memory[progress]){error();if(game.state.phase==='playing')showStep();return;}progress++;$('#memory-progress').textContent=`${progress} / ${puzzle.memory.length}`;if(progress===puzzle.memory.length)done();});}
 if(step===6)bindHold($('#pressure'),elapsed=>{$('#pressure-fill').style.width=`${Math.min(100,pressureValue(elapsed))}%`;},elapsed=>pressureAccepted(elapsed)?done():error());
 if(step===7)document.querySelectorAll('[data-odd]').forEach(b=>b.onclick=()=>Number(b.dataset.odd)===puzzle.odd?done():error());
 if(step===8)$('#sync').onclick=()=>syncAccepted(performance.now()-stepStarted)?done():error();
 if(step===9){$('#cap').onclick=()=>{capOpen=true;$('#cap').classList.add('open');$('#cap').setAttribute('aria-expanded','true');$('#disarm').disabled=false;};bindHold($('#disarm'),elapsed=>{$('#final-fill').style.width=`${Math.min(100,elapsed/20)}%`;if(elapsed>=2000&&capOpen)done();},()=>{if(game.state.phase==='playing'&&game.state.step===9)$('#final-fill').style.width='0%';});}
}
function bindHold(button,onFrame,onRelease){
 button.setAttribute('aria-description','Souris ou espace : maintenir puis relâcher. Entrée : commencer, puis Entrée pour relâcher.');
 function begin(){if(holding||button.disabled||game.state.phase!=='playing')return;holding={button,start:performance.now()};button.classList.add('held');const animate=()=>{if(!holding)return;game.tick();if(game.state.phase!=='playing'){end();return;}onFrame(performance.now()-holding.start);if(holding)holdFrame=requestAnimationFrame(animate);};holdFrame=requestAnimationFrame(animate);}
 function release(cancel=false){if(!holding||holding.button!==button)return;const elapsed=performance.now()-holding.start;holding=null;cancelAnimationFrame(holdFrame);button.classList.remove('held');if(!cancel&&game.state.phase==='playing')onRelease(elapsed);}
 button.onpointerdown=e=>{if(e.button!==0||button.disabled)return;button.setPointerCapture(e.pointerId);begin();};button.onpointerup=()=>release();button.onpointercancel=()=>release(true);button.onlostpointercapture=()=>release(true);
 button.onkeydown=e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();if(e.repeat)return;if(e.key==='Enter'&&holding?.button===button)release();else begin();}};
 button.onkeyup=e=>{if(e.key===' '){e.preventDefault();release();}};button.onblur=()=>release(true);
}
function displayTime(){const ms=game.remaining(),seconds=Math.floor(ms/1000);$('#countdown').innerHTML=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}<span>.${String(Math.floor(ms%1000/10)).padStart(2,'0')}</span>`;document.body.classList.toggle('critical',ms<10000);document.body.style.setProperty('--pulse-time',ms<10000?'.6s':ms<30000?'1s':'1.6s');return ms;}
function loop(){game.tick();if(game.state.phase!=='playing'){end();return;}const ms=displayTime();audio.tick(ms);if(game.state.step===0){document.querySelectorAll('[data-switch]').forEach(b=>{const index=Number(b.dataset.switch);if(matched.has(index))return;const position=switchPosition(performance.now()-stepStarted,index,puzzle.switchPhases[index]);b.style.setProperty('--switch-position',`${position}%`);b.classList.toggle('in-zone',position>=tuning.switchThreshold);});}if(game.state.step===8){const wave=Math.sin((performance.now()-stepStarted)/650);$('#sync-a').style.left=`${50+wave*42}%`;$('#sync-b').style.left=`${50-wave*42}%`;}frame=requestAnimationFrame(loop);}
function end(){if(finished)return;finished=true;cancelAnimationFrame(frame);clearModule();const win=game.state.phase==='won';document.body.dataset.phase=win?'won':'lost';document.body.classList.remove('critical');audio.stop(win);displayTime();updateProgress();$('#armed-text').textContent=win?'DÉSAMORCÉ':'SIGNAL PERDU';$('#module').innerHTML=`<div class="result ${win?'win':''}"><span>${win?'✓ PROTOCOLE TERMINÉ':'✕ TEMPS ÉCOULÉ'}</span><h3>${win?'Respirez.':'Trop tard.'}</h3><p>${win?`Les dix verrous sont ouverts.<br/>${(game.remaining()/1000).toFixed(2).replace('.',',')} secondes restantes.`:`${game.state.step} / 10 verrous ouverts.<br/>Le calme fera la différence.`}</p><button class="play" id="retry">REJOUER <span>↻</span></button></div>`;$('#retry').onclick=start;announce(win?'Bombe désamorcée. Vous avez gagné.':'Temps écoulé. Réessayez.');}
$('#restart').onclick=()=>{if($('#concept').open)$('#concept').close();ready();};$('#sound').onclick=async()=>{try{await audio.mute();$('#sound').setAttribute('aria-pressed',String(!audio.enabled));$('#sound').setAttribute('aria-label',audio.enabled?'Couper le son':'Activer le son');$('#sound span').textContent=audio.enabled?'SON ACTIVÉ':'SON COUPÉ';}catch{announce('Son indisponible sur ce navigateur.');}};
$('#open-concept').onclick=()=>$('#concept').showModal();for(const id of ['close-concept','back-game'])$(`#${id}`).onclick=()=>$('#concept').close();
document.addEventListener('visibilitychange',()=>{if(document.hidden){audio.suspend();if(holding){cancelAnimationFrame(holdFrame);holding.button.classList.remove('held');holding=null;}}else{if(game.state.phase==='playing'){game.tick();if(game.state.phase==='playing')audio.resume();else end();}}});window.addEventListener('pagehide',()=>{cancelAnimationFrame(frame);clearModule();audio.suspend();});
ready();
